### ISSUE TITLE
ChannelPoints GetCustomRewardRedemption returns an exception

### ISSUE THREAD

**Issue by RNGIllSkillz** [TwitchLib/TwitchLib.Api#235] opened 2021-11-13 05:20 UTC
Im trying to figure out how to change redemption status with 
API.Helix.ChannelPoints.UpdateCustomRewardRedemptionStatus() and its a bit confisung.
Twitch api doc says that required query parameters are id, broadcaster_id, reward_id and required body values of string status.
but UpdateCustomRewardRedemptionStatus endpoint for some reasone requires a List<string> redemprionIds and UpdateCustomRewardRedemptionStatusRequest request. How to properly use it?
My code is (wrong):
public void TestDeclineLastRedemtion()
{
 string redemption1ID = "redemption ID";
 var red = API.Helix.ChannelPoints.GetCustomRewardRedemption(BrodcasterID, redemption1ID).Result;
 var status = TwitchLib.Api.Core.Enums.CustomRewardRedemptionStatus.CANCELED;
 API.Helix.ChannelPoints.UpdateCustomRewardRedemptionStatus(BrodcasterID, redemption1ID, red.Data[0].Id, status).Start();
 }

**Comment by Mahsaap** [comment] 2021-11-13 06:26
The list is so you can ask for multiple at a time and get a list of responses. 
Just add the id to a list and use that as the variable. The returned object will be a List as well.

**Comment by RNGIllSkillz** [comment] 2021-11-13 07:56
Got it, thanks! But now
var red = API.Helix.ChannelPoints.GetCustomRewardRedemption(BrodcasterID, rewardID).Result;
is throwing exception:
 1. Your ClientID was invalid/not set.
 2. Your refresh token was invalid.
 3. You requested a username when the server was expecting a user ID.)
 `
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
`

refresh token?

**Comment by Mahsaap** [comment] 2021-11-13 13:31
It's a generic response because it's limited to the errors twitch gives and doesn't handle them all. 

Make sure your token has the scope required stated in the docs.

Have you tried pre release version? Depending on how old of a version your using there was a variable that was changed.

**Comment by RNGIllSkillz** [comment] 2021-11-13 14:11
Yes, my token have the scope that is required for that. Im on version 3.3.0

**Comment by RNGIllSkillz** [comment] 2021-11-14 08:27
I double checked my tokens scope. It have these scopes:
`channel:manage:polls
channel:manage:predictions
channel:manage:redemptions
channel:moderate
channel:read:predictions
channel:read:redemptions
clips:edit`

I also tried to use random token in my code to see the behavior. And with that it returned different exception:
Your request was blocked due to bad credentials (Do you have the right scope for your access token?

So, with my token my request is not getting blocked. Is there a chance that there is an error in GetCustomRewardRedemption endpoint ?

**Comment by swiftyspiffy** [comment] 2021-11-14 08:28
https://dev.twitch.tv/docs/api/reference#update-custom-reward

`The Custom Reward specified by id must have been created by the client_id attached to the user OAuth token.`

Did you make the reward with the client id you're using to update the reward's redemption, or was the reward created using the desktop/website client id (ie twitch.tv)?

**Comment by RNGIllSkillz** [comment] 2021-11-14 08:33
Yes, rewards was made with the same client id, and im not getting errors with UpdateCustomRewardRedemptionStatus. Im trying to get a list of redemptionId with GetCustomRewardRedemption

**Comment by swiftyspiffy** [comment] 2021-11-14 08:52
What are the values of broadcasterID and redemption1ID in these cases?

**Comment by RNGIllSkillz** [comment] 2021-11-14 09:01
broadcasterID = 62651386;
redemption1ID = "693d0956-4126-4563-958c-637a65e847a0";

**Comment by swiftyspiffy** [comment] 2021-11-14 09:10
I'll test this functionality tomorrow and verify it works, then share my sample code here.

**Comment by RNGIllSkillz** [comment] 2021-11-14 09:15
Thank you!

**Comment by RNGIllSkillz** [comment] 2021-11-16 17:47
Any luck ?

**Comment by swiftyspiffy** [comment] 2021-11-16 20:38
Sorry, got delayed. I created a reward with the api, used pubsub to listen to redemptions to get the redemption id, and then used the api to update the redemption status to fulfilled. Here's the code for each section:

### *Create Reward*:
```
var api = new TwitchLib.Api.TwitchAPI();
api.Settings.ClientId = "<CLIENT_ID>";
api.Settings.AccessToken = "<ACCESS_TOKEN>";

var createResp = api.Helix.ChannelPoints.CreateCustomRewardsAsync("<USER_ID>", new TwitchLib.Api.Helix.Models.ChannelPoints.CreateCustomReward.CreateCustomRewardsRequest
{
    Title = "This is a test reward",
    Cost = 10,
    Prompt = "Sample prompt",
    IsEnabled = true,
    IsUserInputRequired = true,
    ShouldRedemptionsSkipRequestQueue = false
}).GetAwaiter().GetResult();
Console.WriteLine($"Reward id: {createResp.Data[0].Id}");
```
```
Reward id: 8f1390e5-54f9-40bc-8d55-0666ba33c2eb
```
### *Listen For Reward Redemption*:
```
private static TwitchLib.PubSub.TwitchPubSub pubsub;
static void Main(string[] args)
{
    pubsub = new TwitchLib.PubSub.TwitchPubSub();
    pubsub.ListenToChannelPoints("<USER_ID>");
    pubsub.OnLog += Pubsub_OnLog;
    pubsub.OnPubSubServiceConnected += Pubsub_OnPubSubServiceConnected;
    pubsub.Connect();
}
private static void Pubsub_OnPubSubServiceConnected(object sender, EventArgs e)
{
    Console.WriteLine($"Connected!");
    pubsub.SendTopics("<ACCESS_TOKEN>");
}

private static void Pubsub_OnLog(object sender, TwitchLib.PubSub.Events.OnLogArgs e)
{
    Console.WriteLine($"[LOG] {e.Data}");
}
```
### *Update Reward Redemption*:
```
var api = new TwitchLib.Api.TwitchAPI();
api.Settings.ClientId = "<CLIENT_ID>";
api.Settings.AccessToken = "<ACCESS_TOKEN>";

var updateResp = api.Helix.ChannelPoints.UpdateRedemptionStatusAsync("<USER_ID>", "8f1390e5-54f9-40bc-8d55-0666ba33c2eb", new System.Collections.Generic.List<string> { "3beabad1-2763-47c0-898b-fc71ee670343" }, new TwitchLib.Api.Helix.Models.ChannelPoints.UpdateCustomRewardRedemptionStatus.UpdateCustomRewardRedemptionStatusRequest
{
    Status = TwitchLib.Api.Core.Enums.CustomRewardRedemptionStatus.FULFILLED
}).GetAwaiter().GetResult();
Console.WriteLine($"Id: {updateResp.Data[0].Id} updated to: {updateResp.Data[0].Status}");
```
Where `8f1390e5-54f9-40bc-8d55-0666ba33c2eb` is the reward id, and `3beabad1-2763-47c0-898b-fc71ee670343` is the redemption id.
```
Id: 3beabad1-2763-47c0-898b-fc71ee670343 updated to: FULFILLED
```

### *Delete Reward*:
```
var api = new TwitchLib.Api.TwitchAPI();
api.Settings.ClientId = "<CLIENT_ID>";
api.Settings.AccessToken = "<ACCESS_TOKEN>";

api.Helix.ChannelPoints.DeleteCustomRewardAsync("<USER_ID>", "8f1390e5-54f9-40bc-8d55-0666ba33c2eb").GetAwaiter().GetResult();
```

**Comment by swiftyspiffy** [comment] 2021-11-16 20:42
As a side note, it looks like you're using an older version. try updating to the latest prerelease version

**Comment by RNGIllSkillz** [comment] 2021-11-17 17:46
Thanks! I was wandering why pubsub was silent, turns out line 
`pubsub.SendTopics("<ACCESS_TOKEN>"); `
was missing. Now I can get redemwtionId with pubsub. Are you comparing internally ClientId and BrodcasterID in UpdateRedemptionStatusAsync? Because I have this error:
`The token provided in the request did not match the associated user. Make sure the token you're using is from the resource owner (streamer? viewer?)`
I think it might be because my <CLIENT_ID> != <USER_ID>. My access token is generated with twitchtokengenerator.com and im currently using TTGs client-id.

**Comment by Mahsaap** [comment] 2021-11-17 19:19
I will also add to this. Some topics will also require the broadcaster token. And that the generator should not be used in production but testing is fine.

**Comment by RNGIllSkillz** [comment] 2021-11-17 21:30
So it seems that in terms of credentials im good
```
ConfigurationReader cReader = new ConfigurationReader(); //json reader
BrodcasterID = cReader.getBotConfigs().BrodcasterId;  //BrodcasterId (62651386)
TwitchAPI API = new TwitchAPI();
API.Settings.ClientId = cReader.getBotConfigs().TApiClientId;         //TTGs client-id
API.Settings.AccessToken = cReader.getBotConfigs().TApiAccessToken;   //generated token with all the scopes
```
but when Im trying to run
```
var updateResp = API.Helix.ChannelPoints.UpdateRedemptionStatusAsync(BrodcasterID, rewardID, new System.Collections.Generic.List<string> { RedemID }, new TwitchLib.Api.Helix.Models.ChannelPoints.UpdateCustomRewardRedemptionStatus.UpdateCustomRewardRedemptionStatusRequest
                {
                    Status = TwitchLib.Api.Core.Enums.CustomRewardRedemptionStatus.CANCELED
                }).GetAwaiter().GetResult();
```

Im getting BadTokenException. And I cannot figure out why, since this id/token combo is working just fine for every other endpoints.

**Comment by swiftyspiffy** [comment] 2021-12-05 01:58
So at this point, I'm pretty convinced the issue is not on the library side, but rather your implementation (I've tested this, and had another broadcaster account test it). The broadcaster id has to be a number string of the broadcaster, and the credentials need to be those of the broadcaster, and the custom reward spawning the redemption needs to have been generated programmatically by the associated client id.

I'm going to close this, but if for some reason you still think the issue is on the library end, feel free to reopen.

**Closed by swiftyspiffy** 2021-12-05 01:58 UTC

**Comment by Reizoky** [comment] 2021-12-29 19:54
Hello. Faced such a problem. Getting the custom rewards goes well, but changing the redemption causes an error.
The library was updated to the latest version via NuGet.
Here is the code

**Comment by Reizoky** [comment] 2021-12-29 20:01
Hello. Faced such a problem. Getting the custom rewards goes well, but changing the redemption causes an error.
The library was updated to the latest version via NuGet.
Here is the code
`
public static async void test()
        {
            var tr = twitchAPI.Auth;

            var user = (await twitchAPI.Helix.Users.GetUsersAsync()).Users[0];
            userId = user.Id;
            var t = (await twitchAPI.Helix.ChannelPoints.GetCustomReward(userId));

            twitchAPI = new TwitchAPI();
            twitchAPI.Settings.ClientId = clientId;
            twitchAPI.Settings.AccessToken = twitchOAuth;

            var rewardIndo = (await twitchAPI.Helix.ChannelPoints.GetCustomRewardRedemption(userId, "9275c87c-ba49-4ac0-b125-af14b303cf87"));

            UpdateCustomRewardRedemptionStatusRequest status = new UpdateCustomRewardRedemptionStatusRequest();
            status.Status = CustomRewardRedemptionStatus.CANCELED;
            var rewardUpdateInfo = (await twitchAPI.Helix.ChannelPoints.UpdateCustomRewardRedemptionStatus(userId, "9275c87c-ba49-4ac0-b125-af14b303cf87",
                new List<string> { "2d2896b6-399a-4687-ab78-933cf70aae37" },
                status));

        //id: 2d2896b6-399a-4687-ab78-933cf70aae37
        //reward_id: 9275c87c-ba49-4ac0-b125-af14b303cf87
        }
`
Errors:

- for "GetCustomRewardRedemption" TwitchLib.Api.Core.Exceptions.BadRequestException: "Your request failed because either:
  1. Your ClientID was invalid / not set.
  2. Your refresh token was invalid.
  3. You requested a username when the server was expecting a user ID. "

- for "UpdateCustomRewardRedemptionStatus" TwitchLib.Api.Core.Exceptions.BadTokenException: "The token provided in the request did not match the associated user. Make sure the token you're using is from the resource owner (streamer? Viewer?)" 

Please answer, I wrote it so badly and\or did not understand something or there is an error in the library.
Sorry if the text is not clear to you. used a translator

**Comment by RNGIllSkillz** [comment] 2021-12-29 20:57
Yes it's annoying as hell. I dont know why twitch did this but in order to change redemption status for reward, reward itself should be created via your bot
