### ISSUE TITLE
Server based access token are generated on every request

### ISSUE THREAD

**Issue by Ebrithil95** [TwitchLib/TwitchLib.Api#170] opened 2021-02-04 08:20 UTC
Currently when using server based access tokens (client_credentials flow) a new access token is created for every api call.
This creates a lot of unneccessary requests and delay.

Instead the expiration time should be stored and a new access token only requested when it is near that expiration time.

**Comment by Syzuna** [comment] 2021-03-11 01:16
This PR has been merged and also a new stable release was made that includes the PR.

If something is still not working as intended pls reopen :)

**Closed by Syzuna** 2021-03-11 01:16 UTC
